"""
ShapeForge vs Imagen Apex Comparison

Side-by-side comparison of chairs generated by:
1. ShapeForge (trained model)
2. Imagen Apex (Gemini + SAM 3D pipeline)
"""

import os
import sys
import base64
import requests
from pathlib import Path
from typing import Optional
from datetime import datetime

import numpy as np
import click
from PIL import Image
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Import generate functions
sys.path.insert(0, str(Path(__file__).parent.parent))
from inference.generate import (
    load_model, 
    generate_with_shapeforge, 
    generate_placeholder_chair,
    save_point_cloud_ply,
    get_device
)


def visualize_point_cloud(points: np.ndarray, ax: plt.Axes, title: str = "") -> None:
    """Render a point cloud on a matplotlib 3D axes."""
    # Color by height
    colors = (points[:, 1] - points[:, 1].min()) / (points[:, 1].max() - points[:, 1].min() + 1e-6)
    
    ax.scatter(
        points[:, 0], 
        points[:, 2],  # Swap Y and Z for better viewing
        points[:, 1], 
        c=colors, 
        cmap='viridis', 
        s=1, 
        alpha=0.6
    )
    
    ax.set_title(title, fontsize=14, fontweight='bold')
    ax.set_xlim([-1, 1])
    ax.set_ylim([-1, 1])
    ax.set_zlim([-1, 1])
    ax.set_xlabel('X')
    ax.set_ylabel('Z')
    ax.set_zlabel('Y')
    
    # Clean up axes
    ax.xaxis.pane.fill = False
    ax.yaxis.pane.fill = False
    ax.zaxis.pane.fill = False


def load_ply_points(ply_path: str) -> np.ndarray:
    """Load points from a PLY file."""
    points = []
    
    with open(ply_path, 'r') as f:
        in_header = True
        vertex_count = 0
        
        for line in f:
            line = line.strip()
            
            if in_header:
                if line.startswith('element vertex'):
                    vertex_count = int(line.split()[-1])
                elif line == 'end_header':
                    in_header = False
            else:
                parts = line.split()
                if len(parts) >= 3:
                    x, y, z = float(parts[0]), float(parts[1]), float(parts[2])
                    points.append([x, y, z])
                    if len(points) >= vertex_count:
                        break
    
    return np.array(points, dtype=np.float32)


def call_imagen_apex(
    prompt: str,
    endpoint_url: str,
    api_key: Optional[str] = None
) -> Optional[np.ndarray]:
    """
    Call Imagen Apex API to generate a 3D model from text.
    
    Returns point cloud as numpy array, or None on failure.
    """
    print(f"📡 Calling Imagen Apex API...")
    print(f"   Endpoint: {endpoint_url}")
    print(f"   Prompt: {prompt}")
    
    # This would call your Imagen Apex pipeline
    # For now, return None to indicate API not available
    
    try:
        # Step 1: Generate image with Gemini (would need separate endpoint)
        # Step 2: Convert to 3D with SAM 3D
        
        # Placeholder - in production this would call your actual API
        headers = {
            "Content-Type": "application/json",
        }
        if api_key:
            headers["X-API-Key"] = api_key
        
        # This is a placeholder - your actual API structure may differ
        response = requests.post(
            endpoint_url,
            json={"prompt": prompt},
            headers=headers,
            timeout=120
        )
        
        if response.status_code == 200:
            data = response.json()
            if 'ply' in data:
                # Decode base64 PLY and parse
                ply_bytes = base64.b64decode(data['ply'])
                # Parse PLY bytes to points...
                return None  # Would need to implement PLY parsing
        
        return None
        
    except Exception as e:
        print(f"   ⚠️ API call failed: {e}")
        return None


@click.command()
@click.option('--shapeforge-checkpoint', '-s', default=None, help='ShapeForge checkpoint path')
@click.option('--imagen-apex-endpoint', '-e', default=None, help='Imagen Apex API endpoint')
@click.option('--imagen-apex-key', '-k', default=None, help='Imagen Apex API key')
@click.option('--prompt', '-p', default='a modern wooden chair', help='Text prompt for Imagen Apex')
@click.option('--output', '-o', default='comparison.png', help='Output image path')
@click.option('--seed', type=int, default=42, help='Random seed')
def main(
    shapeforge_checkpoint: Optional[str],
    imagen_apex_endpoint: Optional[str],
    imagen_apex_key: Optional[str],
    prompt: str,
    output: str,
    seed: int
):
    """
    Generate side-by-side comparison of ShapeForge and Imagen Apex.
    
    Examples:
        python compare.py --shapeforge-checkpoint checkpoints/best.pt
        python compare.py --prompt "ergonomic office chair"
    """
    print("🔄 ShapeForge vs Imagen Apex Comparison")
    print("=" * 50)
    
    device = get_device()
    np.random.seed(seed)
    
    # Generate with ShapeForge
    print("\n🔧 Generating with ShapeForge...")
    
    if shapeforge_checkpoint and Path(shapeforge_checkpoint).exists():
        model = load_model(shapeforge_checkpoint, device)
        shapeforge_points = generate_with_shapeforge(model, device, 1, seed)[0]
        shapeforge_label = "ShapeForge (Trained)"
    else:
        print("   Using placeholder (no checkpoint provided)")
        shapeforge_points = generate_placeholder_chair()
        shapeforge_label = "ShapeForge (Placeholder)"
    
    # Generate with Imagen Apex
    print("\n🌐 Generating with Imagen Apex...")
    
    if imagen_apex_endpoint:
        imagen_points = call_imagen_apex(prompt, imagen_apex_endpoint, imagen_apex_key)
        if imagen_points is not None:
            imagen_label = f"Imagen Apex\n'{prompt}'"
        else:
            print("   API unavailable, using placeholder")
            imagen_points = generate_placeholder_chair()
            # Add some random variation to look different
            imagen_points = imagen_points + np.random.normal(0, 0.05, imagen_points.shape)
            imagen_label = "Imagen Apex (Placeholder)"
    else:
        print("   No endpoint specified, using placeholder")
        imagen_points = generate_placeholder_chair()
        imagen_points = imagen_points + np.random.normal(0, 0.05, imagen_points.shape)
        imagen_label = "Imagen Apex (Placeholder)"
    
    # Create comparison visualization
    print("\n🎨 Creating comparison visualization...")
    
    fig = plt.figure(figsize=(14, 6))
    fig.suptitle("3D Chair Generation Comparison", fontsize=16, fontweight='bold')
    
    # ShapeForge
    ax1 = fig.add_subplot(121, projection='3d')
    visualize_point_cloud(shapeforge_points, ax1, shapeforge_label)
    
    # Imagen Apex
    ax2 = fig.add_subplot(122, projection='3d')
    visualize_point_cloud(imagen_points, ax2, imagen_label)
    
    plt.tight_layout()
    
    # Save
    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(str(output_path), dpi=150, bbox_inches='tight')
    print(f"\n💾 Saved comparison to: {output_path}")
    
    # Also save individual PLY files
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    sf_ply = output_path.parent / f"shapeforge_{timestamp}.ply"
    save_point_cloud_ply(shapeforge_points, str(sf_ply))
    print(f"   ShapeForge PLY: {sf_ply}")
    
    ia_ply = output_path.parent / f"imagen_apex_{timestamp}.ply"
    save_point_cloud_ply(imagen_points, str(ia_ply))
    print(f"   Imagen Apex PLY: {ia_ply}")
    
    print("\n✅ Comparison complete!")


if __name__ == "__main__":
    main()
